production:
  adapter: postgresql
  database: postgresdb_prod
  host: NB-DENE-0019.int.audatex.com
  username: postgres
  password: "lidenise"

development:
  adapter: postgresql
  database: postgresdb_dev
  host: NB-DENE-0019.int.audatex.com
  username: postgres
  password: "lidenise"

test:
  adapter: postgresql
  database: postgresdb_test
  host: NB-DENE-0019.int.audatex.com
  username: postgres
  password: "lidenise"